trigger:
- none

stages:
  - stage: Build
    jobs:
      - job: Build
        displayName: Build job
        pool: br-agent

        steps:

        - script: |
            whereis docker
          # docker inspect --format '{{join .Args " , "}}'
          # docker -v
