trigger:
- azure-pipeline-test

stages:
  - stage: Build
    jobs:
      - job: Build
        pool: br-agent

        steps:
        - task: DockerCompose@1
          displayName: Container registry login
          inputs:
            containerregistrytype: Container Registry
            dockerRegistryEndpoint: docker